# Generated by Django 4.1.5 on 2023-12-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBAirCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.UUIDField()),
                ('name', models.CharField(max_length=10000, null=True)),
                ('pilot', models.CharField(max_length=10000)),
                ('company_address', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBArrivalPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.UUIDField()),
                ('point', models.CharField(max_length=10000, null=True)),
                ('airport_address', models.CharField(max_length=10000, null=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBDeparturePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.UUIDField()),
                ('point', models.CharField(max_length=10000, null=True)),
                ('airport_address', models.CharField(max_length=10000, null=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.UUIDField()),
                ('flight_number', models.IntegerField(null=True)),
                ('pilot', models.CharField(max_length=10000)),
                ('aircompany', models.CharField(max_length=10000, null=True)),
                ('airflight_route', models.CharField(max_length=10000, null=True)),
                ('departure_point', models.CharField(max_length=10000, null=True)),
                ('departure_point_address_airport', models.CharField(max_length=10000, null=True)),
                ('departure_point_latitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('departure_point_longitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('arrival_point', models.CharField(max_length=10000, null=True)),
                ('arrival_point_address_airport', models.CharField(max_length=10000, null=True)),
                ('arrival_point_latitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('arrival_point_longitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('distance_km', models.FloatField(null=True)),
                ('flight_time', models.TimeField(null=True)),
                ('departure_date', models.DateTimeField(null=True)),
                ('departure_time', models.TimeField(null=True)),
                ('arrival_date', models.DateField(null=True)),
                ('arrival_time', models.TimeField(null=True)),
                ('number_of_passengers', models.IntegerField(null=True)),
                ('flight_condition', models.CharField(default='without correction', max_length=10000)),
                ('reason_of_correction', models.CharField(max_length=10000, null=True)),
                ('departure_point_weather', models.CharField(max_length=10000, null=True)),
                ('arrival_point_weather', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBManualControlRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.UUIDField()),
                ('reason', models.CharField(max_length=10000, null=True)),
                ('confirm_request', models.CharField(max_length=10000, null=True)),
                ('old_departure_point', models.CharField(max_length=10000, null=True)),
                ('old_arrival_point', models.CharField(max_length=10000, null=True)),
                ('new_departure_point', models.CharField(max_length=10000, null=True)),
                ('new_departure_latitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('new_departure_longitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('changed_arrival_point', models.CharField(max_length=10000, null=True)),
                ('changed_arrival_latitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('changed_arrival_longitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBPilots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.UUIDField()),
                ('username', models.CharField(max_length=10000)),
                ('password', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address_registration', models.CharField(max_length=10000, null=True)),
                ('company_name', models.CharField(max_length=10000, null=True)),
                ('flight_number', models.IntegerField(null=True)),
                ('departure_point', models.CharField(max_length=10000, null=True)),
                ('arrival_point', models.CharField(max_length=10000, null=True)),
                ('pilot_registration_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.UUIDField()),
                ('first_reason', models.CharField(max_length=10000, null=True)),
                ('second_reason', models.CharField(default='absent', max_length=10000)),
                ('old_departure_point', models.CharField(max_length=10000, null=True)),
                ('old_arrival_point', models.CharField(max_length=10000, null=True)),
                ('new_departure_point', models.CharField(max_length=10000, null=True)),
                ('original_latitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('original_longitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('changed_arrival_point', models.CharField(max_length=10000, null=True)),
                ('corrected_latitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('corrected_longitude', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('weather_new_location', models.CharField(max_length=10000, null=True)),
                ('description_weather', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
